// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: structmessage.proto

package pb

import (
	fmt "fmt"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Format int32

const (
	Format_JSON     Format = 0
	Format_PROTOBUF Format = 1
)

var Format_name = map[int32]string{
	0: "JSON",
	1: "PROTOBUF",
}

var Format_value = map[string]int32{
	"JSON":     0,
	"PROTOBUF": 1,
}

func (x Format) String() string {
	return proto.EnumName(Format_name, int32(x))
}

func (Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2699c8ff9357df6b, []int{0}
}

// StructMessage is a Protobuf based message on top of Message.
// It implements Message interface and can be sent with via a Speaker.
type StructMessage struct {
	Namespace            string             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type                 string             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Uuid                 string             `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UUID                 string             `json:"-"` // Alias for Uuid for backward compatibility
	Status               int64              `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Format               Format             `protobuf:"varint,5,opt,name=format,proto3,enum=pb.Format" json:"format,omitempty"`
	Obj                  []byte             `protobuf:"bytes,6,opt,name=obj,proto3" json:"obj,omitempty"`
	XXX_state            structMessageState `json:"-"` // Custom state for caching
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

// structMessageState holds the runtime state for StructMessage
type structMessageState struct {
	Value any

	JsonCache     []byte
	ProtobufCache []byte
}

func (m *StructMessage) Reset()         { *m = StructMessage{} }
func (m *StructMessage) String() string { return proto.CompactTextString(m) }
func (*StructMessage) ProtoMessage()    {}
func (*StructMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2699c8ff9357df6b, []int{0}
}
func (m *StructMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructMessage.Unmarshal(m, b)
}
func (m *StructMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructMessage.Marshal(b, m, deterministic)
}
func (m *StructMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructMessage.Merge(m, src)
}
func (m *StructMessage) XXX_Size() int {
	return xxx_messageInfo_StructMessage.Size(m)
}
func (m *StructMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StructMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StructMessage proto.InternalMessageInfo

func (m *StructMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *StructMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StructMessage) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *StructMessage) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StructMessage) GetFormat() Format {
	if m != nil {
		return m.Format
	}
	return Format_JSON
}

func (m *StructMessage) GetObj() []byte {
	if m != nil {
		return m.Obj
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Format", Format_name, Format_value)
	proto.RegisterType((*StructMessage)(nil), "pb.StructMessage")
}

func init() { proto.RegisterFile("structmessage.proto", fileDescriptor_2699c8ff9357df6b) }

var fileDescriptor_2699c8ff9357df6b = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x29, 0x2a,
	0x4d, 0x2e, 0xc9, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2a, 0x48, 0x92, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x73, 0xf5, 0x41, 0x2c, 0x88, 0x8c,
	0xd2, 0x62, 0x46, 0x2e, 0xde, 0x60, 0xb0, 0x0e, 0x5f, 0x88, 0x0e, 0x21, 0x19, 0x2e, 0xce, 0xbc,
	0xc4, 0xdc, 0xd4, 0xe2, 0x82, 0xc4, 0xe4, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84,
	0x80, 0x90, 0x10, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0x13, 0x58, 0x02, 0xcc, 0x06, 0x89,
	0x95, 0x96, 0x66, 0xa6, 0x48, 0x30, 0x43, 0xc4, 0x40, 0x6c, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0x92,
	0xc4, 0x92, 0xd2, 0x62, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x28, 0x4f, 0x48, 0x89, 0x8b,
	0x2d, 0x2d, 0xbf, 0x28, 0x37, 0xb1, 0x44, 0x82, 0x55, 0x81, 0x51, 0x83, 0xcf, 0x88, 0x4b, 0xaf,
	0x20, 0x49, 0xcf, 0x0d, 0x2c, 0x12, 0x04, 0x95, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x4f, 0xca, 0x92,
	0x60, 0x53, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0x31, 0xb5, 0x14, 0xb8, 0xd8, 0x20, 0x6a, 0x84, 0x38,
	0xb8, 0x58, 0xbc, 0x82, 0xfd, 0xfd, 0x04, 0x18, 0x84, 0x78, 0xb8, 0x38, 0x02, 0x82, 0xfc, 0x43,
	0xfc, 0x9d, 0x42, 0xdd, 0x04, 0x18, 0x9d, 0x38, 0x1e, 0x3c, 0x92, 0x63, 0x58, 0xf0, 0x58, 0x8e,
	0x31, 0x89, 0x0d, 0xec, 0x31, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x26, 0x05, 0x85,
	0x09, 0x01, 0x00, 0x00,
}

func (m *StructMessage) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovStructmessage(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovStructmessage(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovStructmessage(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovStructmessage(uint64(m.Status))
	}
	if m.Format != 0 {
		n += 1 + sovStructmessage(uint64(m.Format))
	}
	l = len(m.Obj)
	if l > 0 {
		n += 1 + l + sovStructmessage(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovStructmessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStructmessage(x uint64) (n int) {
	return sovStructmessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
